[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "volktg_bot"
dynamic = ["version"]
description = "My telegram bot for fun"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.10"
authors = [
    { name = "Dmitriy Volkov", email = "dimas2301@gmail.com" }
]
classifiers=[
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10"
]
dependencies = [
    "aiogram",
    "asyncpg",
    "dotenv",
    "prettytable"
]

[project.scripts]
volktg_bot = "volktg_bot.__main__:main"

[tool.setuptools.packages.find]
exclude = [
    "tests*",
    "docs*",
    "samples*",
    "rpm*",
    "libs*"
]
